const scalar = type => ({type});
const enumeration = (...values) => ({type: 'string', values});
const array = (items, min = 0) => ({type: 'array', items, min});
const object = fields => ({type: 'object', fields});
const nullable = definition => ({...definition, nullable: true});
const string = scalar('string');
const id = {...string, format: 'id'};
const integer = {...scalar('number'), format: 'integer'};
const number = scalar('number');
const boolean = scalar('boolean');
const contentHash = {...string, format: 'content-hash'};
const timestamp = {...string, format: 'timestamp'};
const contextKind = enumeration('work', 'interest');
const help = enumeration('none', 'hint', 'agent', 'unknown');
const candidate = object({candidateId: id, title: string, decisionQuestion: string, reason: string, preview: string});
const hypothesis = object({candidateId: id, category: enumeration('common-knowledge-gap', 'unknown-concept'), rationale: string, status: enumeration('hypothesis')});
const concept = object({conceptId: id, conceptRevision: integer, label: string});
const content = object({contentId: id, role: enumeration('explanation', 'simulation', 'application', 'failure', 'assessment'), text: string, conceptIds: array(id, 1)});
const decision = object({decisionId: id, question: string, choices: array(string, 2), requiredInformation: array(string, 1), explanationId: id, simulationId: id, applicationId: id, failureId: id, assessmentId: id});
const numericInput = object({inputId: id, unit: string, min: number, max: number, default: number});
const activity = object({activityId: id, stage: enumeration('diagnosis', 'orientation', 'exploration', 'assessment', 'return', 'map'), contentIds: array(id), required: boolean, minutes: {...number, positive: true}});
const criterion = object({criterionId: id, dimension: enumeration('concept', 'prediction-model', 'transfer', 'question', 'choice-meaning'), conceptIds: array(id, 1), contentId: id, mode: enumeration('automatic', 'agent'), rule: string});
const rubric = object({rubricId: id, rubricVersion: integer, criteria: array(criterion, 5)});
const response = object({responseId: id, activityId: id, conceptId: id, conceptRevision: integer, purpose: enumeration('prediction', 'explanation', 'transfer', 'question', 'choice', 'view', 'calculation-error'), attempt: integer, previousResponseId: nullable(id), answer: nullable(string), help, recordedAt: timestamp, visibility: enumeration('before-output', 'after-output', 'unknown')});
const assessment = object({assessmentId: id, responseId: id, criterionId: id, rubricVersion: integer, status: enumeration('pending', 'supported', 'partial', 'not_demonstrated', 'skipped'), reviewer: enumeration('unreviewed', 'automatic', 'agent'), context: string, help});
const observation = object({observationId: id, resultId: id, assessmentId: id, conceptId: id, conceptRevision: integer});
const nextPath = object({pathId: id, lessonId: id, conceptId: id, conceptRevision: integer, reason: string});
const root = (kind, version, fields) => object({kind: {...string, kind}, version: {...number, version}, ...fields});
const diagnostic = root('diagnostic', 1, {diagnosticId: id, profileId: id, contextKind, candidates: {...array(candidate, 1), max: 3}, selection: nullable(id), confirmation: enumeration('confirmed', 'deferred', 'unconfirmed'), hypotheses: array(hypothesis)});
const lesson = root('lesson', 1, {lessonId: id, lessonRevision: integer, profileId: id, diagnosticId: id, candidateId: id, contextKind, concepts: array(concept, 1), content: array(content, 1), decisions: array(decision, 1), inputs: array(numericInput, 1), activities: array(activity, 1), rubric});
const result = root('result', 2, {resultId: id, profileId: id, lessonId: id, lessonRevision: integer, baseMapRevision: integer, sequence: integer, previousResultId: nullable(id), state: enumeration('partial', 'completed'), responses: array(response), assessments: array(assessment), contentHash});
const map = root('map', 2, {profileId: id, revision: integer, lessons: array(lesson), results: array(result), observations: array(observation), nextPaths: array(nextPath)});
export const definitions = {diagnostic, lesson, result, map};
export const bundleDefinition = object({diagnostic, lesson, result, map, previousResult: nullable(result)});
